### ISSUE TITLE
Memory Leak - removed elements

### ISSUE THREAD

**Issue by cesutherland** [fat/bean#31]
bean keeps a private reference to DOM elements in the collected variable, which is cleared on page unload.  This reference is kept even after all listeners have been removed from the element.

**Comment by nnarhinen** [comment]
Hmm, I think some kind of memory leak is still present:

http://jsfiddle.net/6ctpn8gk/ check this example with the Profiles tab open in chrome. Collect heap snapshots after every click to the button. It seems memory consumption is increased by 100k on every click.

With `addEventListener` instead of using bean this problem does not exist: http://jsfiddle.net/6ctpn8gk/1/

**Comment by nnarhinen** [comment]
This becomes a true problem when you use a handler that uses some heavy instance in code. These instances then seem to never be garbage collected due to bean holding on to them even though the div is removed and all other references to the instances are cleared.
